Map<String, List<String>> listBreeds = {
  'CACHORRO': [
    'PUG',
    'SHIH TZU',
    'BULDOGUE',
    'DACHSHUND',
    'PASTOR ALEMÃO',
    'POODLE',
    'ROTTWEILER',
    'LABRADOR',
    'PINSCHER',
    'GOLDEN RETRIEVER',
    'SEM RAÇA DEFINIDA (SRD)',
    'OUTRO',
  ],
  'GATO': [
    'PERSA',
    'SIAMÊS',
    'MAINE COON',
    'ANGORÁ',
    'SPHYNX',
    'RAGDOLL',
    'ASHERA',
    'AMERICAN SHORTHAIR',
    'EXÓTICO',
    'SEM RAÇA DEFINIDA (SRD)',
    'OUTRO',
  ],
  'AVE': [
    'CANÁRIO',
    'CALOPSITA',
    'MANON',
    'PERIQUITO AUSTRALIANO',
    'PAPAGAIO',
    'CACATUA',
    'ARARA',
    'SABIÁ',
    'MARITACA',
    'DIAMANTE GOLD',
    'OUTRO',
  ],
};
